import React from 'react'
import { Link } from 'react-router-dom';
import { resources } from "./assets/data/resources";
//import "./styles/research.scss"


const Resources = () => {

  return (
    <div className="resourceHolder">resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolder

    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolder

    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    resourceHolderresourceHolderresourceHolderresourceHolderresourceHolder
    </div>
  )
}

export default Resources